name: niche_interest_matchmaker_app
description: "VibePulse - Social Activity Discovery App"
publish_to: "none"

version: 1.0.0+25

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI / Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  gap: ^3.0.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0
  confetti: ^0.8.0
  flutter_animate: ^4.5.2
  badges: ^3.1.2
  fl_chart: ^0.70.2

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.8

  # Navigation
  auto_route: ^11.1.0

  # Dependency Injection
  get_it: ^9.2.1
  injectable: ^2.7.1+4

  # Network
  dio: ^5.9.2
  connectivity_plus: ^6.1.4

  # Serialization
  json_annotation: ^4.11.0
  freezed_annotation: ^3.1.0

  # Functional
  dartz: ^0.10.1

  # Maps & Location
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # Local Storage
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

  # Image
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  permission_handler: ^11.3.1
  mobile_scanner: ^7.2.0
  nfc_manager: ^4.1.1
  timeago: ^3.7.0
  collection: ^1.19.1

  # Forms
  reactive_forms: ^18.2.2

  # Environment
  flutter_dotenv: ^6.0.0

  # Icons
  font_awesome_flutter: ^11.0.0
  signalr_netcore: ^1.4.4
  google_sign_in: 6.2.1
  flutter_facebook_auth: ^7.1.6
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  freezed: ^3.2.5
  auto_route_generator: ^10.5.0
  json_serializable: ^6.13.1
  injectable_generator: ^2.12.1

flutter:
  default-flavor: dev
  uses-material-design: true
