// lib/core/utils/app_localizations.dart
import 'package:flutter/material.dart';

/// Simple localization utility for VibePulse demo.
/// Supports English and Vietnamese.
class AppLocalizations {
  AppLocalizations._();

  static final ValueNotifier<String> localeNotifier = ValueNotifier('en');

  static String get currentLocale => localeNotifier.value;

  static String tr(String key) {
    final map = _translations[localeNotifier.value] ?? _translations['en']!;
    return map[key] ?? _translations['en']![key] ?? key;
  }

  static void setLocale(String code) {
    localeNotifier.value = code;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // General
      'app_name': 'VibePulse',
      'save': 'Save',
      'cancel': 'Cancel',
      'done': 'Done',
      'edit': 'Edit',
      'delete': 'Delete',
      'search': 'Search',
      'ok': 'OK',
      'loading': 'Loading...',
      'back': 'Back',
      'close': 'Close',
      'more': 'More',
      'more_options': 'More options',

      // Profile
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'interests': 'Interests',
      'badges_gallery': 'Badges Gallery',
      'unlocked': 'UNLOCKED',
      'activity_history': 'Activity History',
      'view_all': 'VIEW ALL',
      'reputation_score': 'REPUTATION SCORE',
      'created': 'Created',
      'joined': 'Joined',
      'joining': 'Joined',
      'connections': 'Connections',
      'badges': 'Badges',
      'display_name': 'Display Name',
      'username': 'Username',
      'bio': 'Bio',
      'location': 'Location',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile updated successfully!',
      'select_interests': 'Select Interests',

      // Settings
      'settings': 'Settings',
      'preferences': 'PREFERENCES',
      'dark_mode': 'Dark Mode',
      'switch_dark': 'Switch to dark theme',
      'location_services': 'Location Services',
      'allow_location': 'Allow location access',
      'language': 'Language',
      'appearance': 'Appearance',
      'system_default': 'System Default',
      'notifications': 'NOTIFICATIONS',
      'push_notifications': 'Push Notifications',
      'get_updates': 'Get real-time updates',
      'email_notifications': 'Email Notifications',
      'weekly_digest': 'Weekly digest & updates',
      'event_reminders': 'Event Reminders',
      'remind_events': 'Remind before events',
      'account_safety': 'ACCOUNT & SAFETY',
      'privacy_visibility': 'Privacy & Visibility',
      'control_who': 'Control who sees your activity',
      'change_password': 'Change Password',
      'update_password': 'Update your password',
      'payout_settings': 'Payout Settings',
      'manage_earnings': 'Manage your hosting earnings',
      'help_center': 'Help Center',
      'faq_support': 'FAQs and support',
      'terms_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'legal_info': 'Legal information',
      'last_updated': 'Last updated',
      'danger_zone': 'DANGER ZONE',
      'sign_out': 'Sign Out',
      'delete_account': 'Delete Account',
      'cannot_undone': 'This action cannot be undone',
      'select_language': 'Select Language',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'delete_confirm':
          'This will permanently delete your account and all data. This action cannot be undone.',

      // Home
      'tonight_vibes': "Tonight's Vibes",
      'explore': 'Explore',
      'see_all': 'See All',
      'nearby_events': 'Nearby Events',
      'no_events_category': 'No more events found in this category.',
      'current_location': 'CURRENT LOCATION',
      'join_vibe': 'JOIN VIBE',

      // Vibe Match
      'vibe_match_title': 'Vibe Match',
      'vibe_match_label': 'MATCH',
      'vibe_match_headline': 'Great Alignment!',
      'vibe_match_subtitle':
          'You match well with this group\'s energy and interests.',
      'vibe_match_why': 'Why you match',
      'vibe_match_summary_title': 'Group vibe summary',
      'vibe_match_summary_body':
          'A laid-back group looking for casual evening kickarounds followed by late-night coffee runs. High energy but very welcoming to newcomers.',
      'vibe_match_going': 'going',
      'vibe_match_join_event': 'Join Event',
      'vibe_match_explore_matches': 'Explore Matches',
      'vibe_match_reason_football': 'Football Fans',
      'vibe_match_reason_night': 'Night Owls',
      'vibe_match_reason_nearby': 'Nearby (2km)',
      'vibe_match_reason_coffee': 'Coffee Lovers',
      'vibe_match_joined_title': 'You are in',
      'vibe_match_joined_headline': 'Spot reserved for tonight',
      'vibe_match_joined_body':
          'You joined the event successfully. We\'ll keep you posted on updates from the host.',
      'your_top_matches': 'Your Top Matches',
      'top_matches_subtitle':
          'Based on your recent vibes and shared interests, we think you\'d connect well with these folks.',
      'reliable': 'Reliable',
      'new': 'New',
      'late_risk': 'Late risk',
      'view_profile': 'View Profile',
      'shared': 'Shared',
      'no_matches_yet': 'No matches available yet.',
      'match': 'Match',
      'miles_short': 'mi',
      'open_group_vibe': 'Open Group Vibe',
      'open_user_detail': 'Open User Detail',
      'open_match_details': 'Open Match Details',
      'vibe_check_title': 'Vibe Check',
      'vibe_check_loading_title': 'AI is analyzing the vibe...',
      'vibe_check_loading_desc':
          'Comparing interests, bio, and other compatibility signals.',
      'vibe_check_error_title': 'Unable to view this vibe',
      'vibe_check_with': 'Vibe with',
      'strengths': 'Strengths',
      'considerations': 'Considerations',
      'conversation_starters': 'Conversation starters',
      'date_ideas': 'Date ideas to try',
      'verdict': 'Verdict',
      'verdict_strong': 'Worth a try',
      'verdict_medium': 'Could be worth trying',
      'verdict_low': 'Learn more first',
      'personality_take': 'What this person is like',
      'compatibility_conclusion': 'Compatibility conclusion',
      'date_recommendation': 'Should you invite them out?',
      'next_step': 'Next step',
      'score_breakdown': 'Score breakdown',
      'bio_label': 'Bio',
      'lifestyle': 'Lifestyle',
      'event': 'Event',
      'common_interests': 'Common interests',
      'group_vibe_check_title': 'Group Vibe Check',
      'group_vibe_loading_title': 'AI is reading the group vibe...',
      'group_vibe_loading_desc':
          'Comparing participants, event themes, and safety signals.',
      'group_vibe_error_title': 'Unable to view this group vibe',
      'update_profile': 'Update profile',
      'back_to_event': 'Back to event',
      'group_vibe_empty_error':
          'This event does not have enough data to analyze the group vibe yet.',
      'group_vibe_bad_request':
          'This event needs more members, or your profile needs more bio/interests.',
      'group_vibe_access_denied':
          'You need to be approved for this event before viewing the group vibe.',
      'group_strengths': 'Group strengths',
      'watchouts': 'Watchouts',
      'suggested_actions': 'Suggested actions to try',
      'members': 'members',
      'analyzed': 'analyzed',
      'group_recommendation_title': 'Is this group right for you?',
      'breakdown': 'Breakdown',
      'member_compatibility': 'Member compatibility',
      'interest_alignment': 'Interest alignment',
      'event_fit': 'Event fit',
      'social_comfort': 'Social comfort',
      'location_fit': 'Location fit',
      'group_reliability': 'Group reliability',
      'top_matches_in_group': 'Top matches in the group',
      'no_group_top_matches': 'No standout members to suggest yet.',
      'member': 'Member',
      'fallback_insight_computed':
          'Insight was generated from the computed fallback data.',
      'fallback_insight_prefix': 'Fallback insight',
      'match_details_title': 'Match Details',
      'high_compatibility_found': 'High compatibility found',
      'compatibility_deep_dive': 'Compatibility Deep Dive',
      'activity_style': 'Activity Style',
      'schedule_match': 'Schedule Match',
      'competitive': 'Competitive',
      'casual': 'Casual',
      'intense': 'Intense',
      'match_strengths_desc':
          'Strong match in sports. Both prefer high-intensity weekend activities and share similar skill levels in tennis.',
      'match_considerations_desc':
          'Contains 2 new users to the platform. Less historical data available for schedule reliability.',
      'how_you_compare_to_group': 'How you compare to group',
      'your_score': 'Your Score',
      'group_avg': 'Group Avg',
      'you_top_group': 'You are in the top 15% for this group',
      'avg': 'Avg',
      'group_analysis': 'Group Analysis',
      'exceptional_vibe': 'Exceptional Vibe',
      'exceptional_vibe_desc':
          'This group has incredibly high energy alignment. Perfect for long, active outings.',
      'strongest_match': 'Strongest Match',
      'low_pace_match': 'Low Pace Match',
      'group_personality': 'Group Personality',
      'group_personality_desc':
          'The majority of this group prefers an energetic, fast-paced environment. Consider adjusting the route to accommodate a more casual pace.',
      'suggest_route_adjustment': 'Suggest Route Adjustment',
      'invite_to_event': 'Invite to Event',
      'high': 'High',
      'compatibility': 'Compatibility',
      'reputation': 'Reputation',
      'about_user': 'About Sarah',
      'about_user_desc':
          'Always down for a spontaneous coffee run or a long hike at the greenbelt. Looking for folks who enjoy trying new food spots and deep conversations over matcha.',
      'recent_activity': 'Recent Activity',
      'hosted_upper': 'HOSTED',
      'attended_upper': 'ATTENDED',
      'last_week': 'Last week',
      'two_weeks_ago': '2 weeks ago',
      'meetups': 'Meetups',

      // Check-in
      'checkin_feature_title': 'Meetup Verified',
      'checkin_title': 'Check-in',
      'checkin_choose_title': 'Choose Check-in',
      'checkin_verifying_page_title': 'Verifying Check-in',
      'checkin_complete_title': 'Check-in Complete',
      'checkin_trust_profile_title': 'Trust Profile',
      'checkin_nav_explore': 'Explore',
      'checkin_nav_meetups': 'Meetups',
      'checkin_nav_scan': 'Scan',
      'checkin_nav_trust': 'Trust',
      'checkin_method_section': 'Check-in method',
      'checkin_verified_label': 'Verified',
      'checkin_method_hint':
          'Choose the fastest available option at the venue.',
      'checkin_starts_in': 'Starts in 15:00',
      'checkin_meeting_point': 'Meeting Point',
      'checkin_required_note':
          'Check-in is required to maintain your trust score',
      'checkin_check_in': 'Check-in',
      'checkin_chat': 'Chat',
      'checkin_map': 'Map',
      'checkin_participants': 'Participants',
      'checkin_confirmed_count': '3 Confirmed',
      'checkin_method_title': 'How would you like to check in?',
      'checkin_method_subtitle':
          'Choose the method available at the meetup location',
      'checkin_qr_method': 'QR Check-in',
      'checkin_qr_method_desc': 'Fast and easy QR verification',
      'checkin_nfc_method': 'NFC Check-in',
      'checkin_nfc_method_desc': 'Tap your phone near the NFC tag',
      'checkin_recommended': 'RECOMMENDED',
      'checkin_recommended_title': 'Recommended',
      'checkin_tap_to_verify': 'Tap to verify',
      'checkin_qr_home_desc': 'Scan the event QR code with your camera.',
      'checkin_nfc_home_desc': 'Hold your phone near the event NFC tag.',
      'checkin_qr_home_footnote': 'Best for hosted events and check-in desks.',
      'checkin_qr_method_footnote': 'Best for event check-in desks.',
      'checkin_nfc_home_footnote': 'Works when NFC is enabled on your device.',
      'checkin_nfc_method_footnote': 'Use NFC when a venue tag is available.',
      'checkin_gps_verified': 'GPS Verified',
      'checkin_distance': 'Distance',
      'checkin_location_auto_verified':
          'Your location will be verified automatically',
      'checkin_secure_checkin': 'Secure check-in',
      'checkin_time': 'Time',
      'checkin_location': 'Location',
      'checkin_confirmed': 'Confirmed',
      'checkin_qr_scan_title': 'Scan the QR at the meetup location',
      'checkin_qr_scan_hint': 'Position the QR code within the frame',
      'checkin_qr_frame_hint': 'Position the QR code inside the frame.',
      'checkin_qr_requesting_camera': 'Requesting camera access',
      'checkin_qr_camera_needed':
          'Camera permission is needed to scan the QR code.',
      'checkin_qr_permission_denied': 'Camera permission denied',
      'checkin_qr_permission_required':
          'Camera permission is required to scan the event QR code.',
      'checkin_retry': 'Retry',
      'checkin_qr_detected': 'QR code detected',
      'checkin_preparing_verification': 'Preparing secure verification...',
      'checkin_qr_unable_to_scan': 'Unable to scan QR code',
      'checkin_qr_scan_error':
          'Something went wrong while scanning. Please try again.',
      'checkin_qr_failed': 'QR check-in failed. Please try again.',
      'checkin_qr_scan_heading': 'Scan the event QR code',
      'checkin_qr_scan_desc':
          'Allow the camera to focus on the code at the check-in desk.',
      'checkin_camera_ready': 'Camera ready',
      'checkin_qr_camera_ready_desc':
          'Keep the QR code flat and inside the frame until verification completes.',
      'checkin_demo_verify': 'Demo verify',
      'checkin_verifying_title': 'Verifying your arrival...',
      'checkin_verifying_desc': 'Securely checking location and time',
      'checkin_gps_active': 'GPS Active',
      'checkin_encrypted': 'Encrypted',
      'checkin_demo_result': 'Show result',
      'checkin_nfc_failed': 'NFC check-in failed. Please try again.',
      'checkin_nfc_checking': 'Checking NFC',
      'checkin_nfc_checking_desc':
          'Checking whether NFC is available on this device.',
      'checkin_nfc_preparing': 'Preparing NFC scanner',
      'checkin_nfc_ready': 'Ready to scan',
      'checkin_nfc_ready_desc': 'Hold your phone near the NFC tag to check in.',
      'checkin_nfc_detected': 'NFC tag detected',
      'checkin_nfc_unsupported': 'NFC is not supported',
      'checkin_nfc_unsupported_desc':
          'This device does not support NFC check-in.',
      'checkin_nfc_disabled': 'NFC is turned off',
      'checkin_nfc_disabled_desc':
          'Enable NFC in device settings and try again.',
      'checkin_nfc_unable_to_start': 'Unable to start NFC',
      'checkin_nfc_start_error':
          'Something went wrong while starting NFC scanning.',
      'checkin_nfc_hint': 'Keep the top of your phone close to the NFC tag.',
      'checkin_nfc_waiting_title': 'Tap your phone near the NFC tag',
      'checkin_nfc_waiting_desc': 'Waiting for detection...',
      'checkin_device_status': 'Device Status',
      'checkin_nfc_result_title': 'Verified',
      'checkin_nfc_result_desc': 'Check-in complete',
      'checkin_result_success_message': 'You have successfully checked in.',
      'checkin_already_checked_in': 'Already checked in',
      'checkin_not_verified': 'Check-in not verified',
      'checkin_attendance_verified': 'Attendance verified',
      'checkin_already_verified_event': 'Already verified for this event',
      'checkin_verified_status': 'Check-in verified',
      'checkin_method_label': 'Method',
      'checkin_xp_awarded': '+15 XP added to your trust score',
      'checkin_view_trust': 'View Trust Profile',
      'checkin_reputation_level': 'Reputation level: Elite Explorer',
      'checkin_trust_score': 'Trust Score',
      'checkin_top_percent': 'Top 2% of the community this month',
      'checkin_attendance_rate': 'Attendance Rate',
      'checkin_meetup_streak': 'Meetup Streak',
      'checkin_earned_badges': 'Earned Badges',
      'checkin_missing_context': 'This check-in is missing meetup context.',
      'checkin_missing_qr_context': 'Missing match context for QR check-in.',
      'checkin_missing_nfc_context': 'Missing match context for NFC check-in.',
      'checkin_missing_method_context_prefix': 'Missing match context for',
      'checkin_already_checked_in_meetup':
          'You have already checked in for this meetup.',
      'checkin_not_available_now': 'Check-in is not available right now.',
      'checkin_method_not_available':
          'check-in is not available for this meetup.',
      'checkin_method_disabled': 'check-in is currently disabled.',
      'checkin_not_participant': 'You are not a participant of this meetup.',
      'checkin_join_not_approved':
          'Your join request has not been approved yet.',
      'checkin_match_cancelled': 'This meetup is no longer active.',
      'checkin_outside_time_window':
          'Check-in is only available near the meetup time.',
      'checkin_location_not_supported':
          'This meetup does not have a supported check-in location.',
      'checkin_no_active_method':
          'No check-in method is active for this meetup.',
      'checkin_no_active_nfc': 'No active NFC tag is available at this venue.',
      'checkin_no_active_qr': 'No active QR code is available at this venue.',
      'checkin_missing_gps_coordinates':
          'The venue is missing GPS coordinates for QR check-in.',
      'checkin_missing_qr_radius': 'The venue is missing a QR check-in radius.',
      'checkin_service_unavailable': 'Check-in service is not available.',
      'checkin_unable_current_location':
          'Unable to get current GPS location. Please try again.',
      'checkin_hold_device_near_nfc':
          'Hold your device near the event NFC tag.',
      'checkin_nfc_turned_off_try_again':
          'NFC is turned off. Enable NFC and try again.',
      'checkin_unable_start_nfc_try_again':
          'Unable to start NFC scanning. Please try again.',
      'checkin_location_service_required':
          'Location service is required for QR check-in.',
      'checkin_location_permission_required':
          'Location permission is required for QR check-in.',
      'checkin_verified_ios_alert': 'Check-in verified.',
      'checkin_checked_in_title': 'You are checked in',
      'checkin_checked_in_desc':
          'Your arrival has been verified. Enjoy the meetup.',
      'checkin_auto_verify_note':
          'NFC tag and time window will be checked automatically.',
      'checkin_fallback_title': 'Meetup check-in',
      'checkin_fallback_location_name': 'Event venue',
      'checkin_fallback_location_address':
          'Location will be verified by the venue.',
      'checkin_fallback_time': 'Scheduled meetup',
      'checkin_member_verified': 'Verified Member',
      'checkin_member_top_contributor': 'Top Contributor',
      'checkin_member_new': 'New Member',
      'checkin_status_arrived': 'Arrived',
      'checkin_status_pending': 'Pending',
      'checkin_status_late': 'Late',
      'checkin_status_late_risk': 'Late Risk',
      'checkin_status_no_show': 'No-show',
      'checkin_badge_early_bird': 'Early Bird',
      'checkin_badge_reliable_host': 'Reliable Host',
      'checkin_badge_explorer': 'Explorer',
      'checkin_badge_top_guest': 'Top Guest',

      // Find in Crowd
      'finder_title': 'Find In Crowd',
      'finder_find_in_crowd': 'Find in Crowd',
      'finder_start': 'Start Finding',
      'finder_cancel': 'Cancel',
      'finder_waiting': 'Waiting',
      'finder_accept': 'Share Temporary Location',
      'finder_decline': 'Not Now',
      'finder_stop': 'Stop Finding',
      'finder_continue': 'Continue',
      'finder_back_to_meeting': 'Back to Meeting',
      'finder_find_again': 'Find Again',
      'finder_temporary_live_location': 'Temporary live location',
      'finder_request_title': 'Finder Request',
      'finder_live_location_request': 'Live location request',
      'finder_request_expired': 'Finder request expired.',
      'finder_request_cancelled': 'Finder request cancelled.',
      'finder_request_was_cancelled': 'Finder request was cancelled.',
      'finder_request_declined': 'Finder request declined.',
      'finder_request_ended': 'Finder request ended.',
      'finder_request_sent': 'Request sent',
      'finder_waiting_response': 'Waiting for response...',
      'finder_waiting_accept_prefix': 'Waiting for',
      'finder_waiting_accept_suffix': 'to accept...',
      'finder_location_starts_after_accept':
          'Location sharing starts only after they accept this request.',
      'finder_cancel_request': 'Cancel Request',
      'finder_request_expired_short': 'Request expired',
      'finder_request_expires_in': 'Request expires in',
      'finder_finding': 'Finding',
      'finder_finding_prefix': 'Finding',
      'finder_waiting_location': 'Waiting',
      'finder_live': 'Live',
      'finder_waiting_shared_location': 'Waiting for shared location',
      'finder_away': 'away',
      'finder_reconnecting': 'Reconnecting',
      'finder_weak_gps': 'Weak GPS',
      'finder_live_signal': 'Live signal',
      'finder_stale_location_note':
          'Waiting for the latest partner location. Sharing resumes when both apps are active.',
      'finder_final_guidance_note':
          'Final guidance is available. Keep moving slowly and look around visually near the last few meters.',
      'finder_active_sharing_note':
          'Live location sharing is active. Follow the direction card until you are close enough for final guidance.',
      'finder_open_final_guidance': 'Open Final Guidance',
      'finder_final_guidance_locked': 'Final Guidance Unlocks Within 30m',
      'finder_stop_sharing': 'Stop Sharing',
      'finder_nearby': 'Nearby',
      'finder_final_approach': 'Final approach',
      'finder_nearby_label': 'nearby',
      'finder_toward_marker': 'toward marker',
      'finder_very_close': 'Very close',
      'finder_they': 'They',
      'finder_should_be_around': 'should be right around you.',
      'finder_is_close_keep_moving': 'is close. Keep moving toward the marker.',
      'finder_look_around_note':
          'Look around, wave, or message them. GPS can drift in the last few meters.',
      'finder_distance_updates_note':
          'Distance updates live from GPS. Walk slowly so Finder can keep the arrow stable.',
      'finder_visual_title': 'Visual Finder',
      'finder_gps_based_direction': 'GPS-based direction',
      'finder_approx_direction': 'approximate direction',
      'finder_exit_ar': 'Exit AR',
      'finder_stop_short': 'Stop',
      'finder_ended_title': 'Finder Ended',
      'finder_session_expired': 'Session expired',
      'finder_location_stopped': 'Location sharing stopped',
      'finder_session_expired_title': 'Finder session expired',
      'finder_ended_panel_title': 'Finder ended',
      'finder_ended_message':
          'Your temporary location is no longer shared for this finder session.',
      'finder_keep_finding': 'Keep Finding',
      'finder_your_partner': 'your partner',
      'finder_stop_sharing_question': 'Stop sharing location?',
      'finder_stop_message_prefix':
          'This ends the finder session for both you and',
      'finder_stopping': 'Stopping...',
      'finder_open_from_event': 'Open from an event',
      'finder_choose_member_first': 'Choose a checked-in event member first',
      'finder_continue_event_members': 'Continue to event members',
      'finder_consent_flow_desc':
          'Finder is a consent-based live GPS flow for two people in the same event.',
      'finder_back_to_events': 'Back to Events',
      'finder_view_members': 'View Members',
      'finder_find_question_prefix': 'Find',
      'finder_find_question_suffix': 'in the crowd?',
      'finder_start_desc_prefix': 'You and',
      'finder_start_desc_suffix':
          'will share approximate locations temporarily to find each other faster.',
      'finder_you': 'You',
      'finder_request_wants_title_suffix': 'wants to find you in the crowd',
      'finder_request_wants_desc_suffix':
          'wants to share temporary approximate locations so you can find each other faster.',
      'finder_for_finding_only': 'For finding only',
      'finder_safety_notice':
          'Temporary sharing ends automatically after 10 minutes. You can stop anytime.',
      'finder_guidance_keep_apps_open':
          'Keep both apps open so Finder can receive live updates.',
      'finder_signal_stale': 'Signal is stale. Ask them to keep the app open.',
      'finder_gps_weak_open_area':
          'GPS is weak. Move near an open area for steadier guidance.',
      'finder_no_target_position': 'No target position yet',
      'finder_camera_note_prefix': 'GPS-based approximate direction to',
      'finder_camera_note_suffix': 'Keep scanning visually when you get close.',
      'finder_distance': 'Distance',
      'finder_direction': 'Direction',
      'finder_current_gps_position': 'Current GPS position',
      'finder_gps_permission_required': 'GPS permission required',
      'finder_allow_location_start':
          'Allow location access to start the finder.',
      'finder_getting_location': 'Getting location...',
      'finder_refresh_gps': 'Refresh GPS',
      'finder_allow_gps_access': 'Allow GPS Access',
      'finder_live_participant': 'Live finder participant',
      'finder_sharing': 'Sharing',
      'finder_location_permission_needed':
          'Location permission is needed to use Finder.',
      'finder_gps_accuracy_weak':
          'GPS accuracy is too weak. Move near an open area and try again.',
      'finder_session_expired_message': 'Finder session expired.',
      'finder_location_sharing_stopped': 'Location sharing was stopped.',
      'finder_gps_off': 'GPS is off. Turn on GPS to use Finder.',
      'finder_enable_location_settings':
          'Enable location in app settings to use Finder.',
      'finder_session_inactive':
          'This Finder session has ended or is no longer active.',
      'finder_session_no_access':
          'You no longer have access to this Finder session.',
      'finder_session_not_found': 'This Finder session was not found.',
      'finder_member_not_available':
          'This person is not available for Finder right now.',
      'finder_request_expired_error': 'This request has expired.',
      'finder_session_conflict':
          'One of you is already in another Finder session.',
      'finder_request_already_exists':
          'You already have a pending Finder request.',
      'finder_north': 'North',
      'finder_north_east': 'North-east',
      'finder_east': 'East',
      'finder_south_east': 'South-east',
      'finder_south': 'South',
      'finder_south_west': 'South-west',
      'finder_west': 'West',
      'finder_north_west': 'North-west',
      'finder_walk_toward': 'Walk toward',
      'finder_move': 'Move',
      'finder_toward': 'toward',
      'finder_keep_straight': 'Keep going straight',
      'finder_turn_right': 'Turn right',
      'finder_turn_around': 'Turn around',
      'finder_turn_left': 'Turn left',
      'finder_go_straight_for': 'Go straight for',
      'finder_slight_right_then': 'Slight right, then',
      'finder_turn_right_then': 'Turn right, then',
      'finder_turn_around_then': 'Turn around, then',
      'finder_turn_left_then': 'Turn left, then',
      'finder_slight_left_then': 'Slight left, then',
      'finder_approx_compass': 'Approximate compass direction',
      'finder_phone_heading': 'Direction follows your phone heading',
      'finder_movement_heading': 'Direction follows your movement',
      'finder_straight_ahead': 'Straight ahead',
      'finder_right': 'right',
      'finder_left': 'left',
      'finder_turn_degrees': 'Turn',
      'finder_degrees': 'degrees',
      'finder_move_closer_unlock': 'Move closer to unlock final guidance.',
      'finder_improving_accuracy':
          'Improving location accuracy before final guidance.',
      'finder_waiting_latest_partner':
          'Waiting for the latest partner location before final guidance.',
      'finder_gps_ready_final': 'GPS is ready for final guidance.',

      // Map
      'search_placeholder': 'Search vibe, location or category...',
      'no_vibes_found': 'No public vibes found here.',

      // Activity
      'my_activity': 'My Activity',
      'hosting': 'Hosting',
      'hosted': 'Hosted',
      'attending': 'Attending',
      'past': 'Past',
      'no_events_yet': 'No events here yet',
      'starts_in_days': 'Starts in 2 days',
      'ended': 'Ended',
      'manage': 'Manage',
      'check_in': 'Check In',
      'rate_experience': 'Rate Experience',

      // Create Event
      'create_vibe': 'Create Vibe',
      'whats_vibe': "What's the Vibe?",
      'give_persona': 'Give your event a persona',
      'event_category': 'Event Category',
      'vibe_tags': 'Vibe Tags',
      'schedule_size': 'Schedule & Size',
      'when_how_many': 'When and how many?',
      'destination': 'The Destination',
      'where_happening': 'Where is it happening?',
      'create_event_title_new': 'Create Event',
      'event_hero_title': 'Build a premium event profile',
      'event_hero_subtitle':
          'Balanced fields, clear hierarchy, and smooth interaction.',
      'event_section_core': 'Core Details',
      'event_section_core_subtitle': 'Identity, category, tags, and media.',
      'event_section_schedule': 'Schedule & Capacity',
      'event_section_schedule_subtitle':
          'Start/end timeline and participant limits.',
      'event_section_location': 'Location',
      'event_section_location_subtitle': 'Place details and map coordinates.',
      'event_section_advanced': 'Advanced Metadata',
      'event_section_advanced_subtitle':
          'Host, status, visibility, and AI score.',
      'event_field_id': 'Event ID',
      'event_field_title': 'Title',
      'event_field_title_hint': 'What is the vibe?',
      'event_field_description': 'Description',
      'event_field_description_hint':
          'Describe who should join and what to expect.',
      'event_field_category': 'Category',
      'event_field_vibe_tags': 'Vibe Tags',
      'event_field_add_tag': 'Add tag',
      'event_field_add_tag_hint': 'Chill, Competitive, Networking...',
      'event_field_photo_urls': 'Photo URLs',
      'event_field_add_photo_url': 'Add photo URL',
      'event_field_start_date': 'Start date',
      'event_field_start_time': 'Start time',
      'event_field_end_date': 'End date',
      'event_field_end_time': 'End time',
      'event_field_max_participants': 'Max participants',
      'event_field_current_participants': 'Current participants',
      'event_field_search_place': 'Search place',
      'event_field_search_place_hint': 'Type at least 2 characters...',
      'event_field_location_name': 'Location name',
      'event_field_location_name_hint': 'District 1 Center',
      'event_field_location_address': 'Address',
      'event_field_location_address_hint': 'Ho Chi Minh City, Vietnam',
      'event_field_latitude': 'Latitude',
      'event_field_longitude': 'Longitude',
      'event_field_host_id': 'Host ID',
      'event_field_host_name': 'Host name',
      'event_field_host_avatar': 'Host avatar URL',
      'event_field_place_id': 'Place ID',
      'event_field_place_id_hint': 'Optional external place id',
      'event_field_status': 'Status',
      'event_field_is_elite_only': 'Elite only visibility',
      'event_field_is_public': 'Public visibility',
      'event_field_is_joined': 'Joined by current user',
      'event_field_match_score': 'Match score',
      'event_field_participant_ids': 'Participant IDs',
      'event_field_participant_ids_hint': 'user-101, user-202...',
      'event_field_created_at': 'Created at',
      'event_status_draft': 'Draft',
      'event_status_active': 'Active',
      'event_status_cancelled': 'Cancelled',
      'event_status_completed': 'Completed',
      'event_category_sports': 'Sports',
      'event_category_dining': 'Dining',
      'event_category_social': 'Social',
      'event_category_arts': 'Arts',
      'event_category_outdoors': 'Outdoors',
      'event_category_gaming': 'Gaming',
      'event_create_button': 'Create Event',
      'event_create_loading': 'Creating event...',
      'event_create_success': 'Event created successfully!',
      'event_create_error': 'Error',
      'event_validation_title_description':
          'Please enter title and description.',
      'event_validation_location': 'Please enter location name and address.',
      'event_validation_end_time':
          'End date/time must be after start date/time.',
      'edit_event_title': 'Edit Event',
      'edit_event_loading': 'Saving changes...',
      'edit_event_success': 'Event updated successfully!',
      'edit_event_error': 'Error updating event',
      'edit_event_validation_capacity':
          'Capacity cannot be lower than the current number of participants ({current}).',
      'edit_event_read_only_fields':
          'Location and schedule are locked after event creation to prevent participant confusion.',

      // New additions for UI
      'appearance_desc':
          'Appearance settings are currently synced with Dark Mode toggle.',
      'privacy': 'Privacy',
      'privacy_desc':
          'Privacy & Visibility settings will be implemented in the next release.',
      'change_password_desc':
          'An email with instructions to change your password has been sent.',
      'payout': 'Payout',
      'payout_desc': 'Your Stripe account is currently connected successfully.',
      'help_desc': 'Redirecting to support portal...',
      'terms': 'Terms',
      'terms_desc': 'Loading terms of service...',
      'version': 'Version 1.0.0 (Build 42)',
      'made_with': 'Made with 💜 in HCMC',
      'language_changed': 'Language changed to',
      'your_display_name': 'Your display name',
      'name_required': 'Name is required',
      'your_username': 'Your username',
      'username_required': 'Username is required',
      'email': 'EMAIL',
      'your_email': 'Your email',
      'tell_people': 'Tell people about yourself...',
      'your_city': 'Your city',
      'tap_change_photo': 'Tap to change photo',
      'avatar_updated': 'Avatar updated!',
      'message': 'Message',
      'follow': 'Follow',
      'following': 'Following',
    },
    'vi': {
      // General
      'app_name': 'VibePulse',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'done': 'Xong',
      'edit': 'Sửa',
      'delete': 'Xóa',
      'search': 'Tìm kiếm',
      'ok': 'OK',
      'loading': 'Đang tải...',
      'back': 'Quay lại',
      'close': 'Đóng',
      'more': 'Thêm',
      'more_options': 'Tùy chọn khác',

      // Profile
      'profile': 'Hồ Sơ',
      'edit_profile': 'Chỉnh Sửa Hồ Sơ',
      'interests': 'Sở Thích',
      'badges_gallery': 'Bộ Sưu Tập Huy Hiệu',
      'unlocked': 'ĐÃ MỞ',
      'activity_history': 'Lịch Sử Hoạt Động',
      'view_all': 'XEM TẤT CẢ',
      'reputation_score': 'ĐIỂM UY TÍN',
      'created': 'Đã tạo',
      'joined': 'Đã tham gia',
      'joining': 'Đã tham gia',
      'connections': 'Kết nối',
      'badges': 'Huy hiệu',
      'display_name': 'Tên hiển thị',
      'username': 'Tên người dùng',
      'bio': 'Tiểu sử',
      'location': 'Vị trí',
      'save_changes': 'Lưu Thay Đổi',
      'profile_updated': 'Hồ sơ đã cập nhật thành công!',
      'select_interests': 'Chọn Sở Thích',

      // Settings
      'settings': 'Cài Đặt',
      'preferences': 'TÙY CHỌN',
      'dark_mode': 'Chế Độ Tối',
      'switch_dark': 'Chuyển sang giao diện tối',
      'location_services': 'Dịch Vụ Vị Trí',
      'allow_location': 'Cho phép truy cập vị trí',
      'language': 'Ngôn Ngữ',
      'appearance': 'Giao Diện',
      'system_default': 'Mặc Định Hệ Thống',
      'notifications': 'THÔNG BÁO',
      'push_notifications': 'Thông Báo Đẩy',
      'get_updates': 'Nhận cập nhật thời gian thực',
      'email_notifications': 'Thông Báo Email',
      'weekly_digest': 'Tóm tắt & cập nhật hàng tuần',
      'event_reminders': 'Nhắc Nhở Sự Kiện',
      'remind_events': 'Nhắc nhở trước sự kiện',
      'account_safety': 'TÀI KHOẢN & BẢO MẬT',
      'privacy_visibility': 'Quyền Riêng Tư',
      'control_who': 'Kiểm soát ai xem hoạt động của bạn',
      'change_password': 'Đổi Mật Khẩu',
      'update_password': 'Cập nhật mật khẩu của bạn',
      'payout_settings': 'Cài Đặt Thanh Toán',
      'manage_earnings': 'Quản lý thu nhập từ tổ chức',
      'help_center': 'Trung Tâm Trợ Giúp',
      'faq_support': 'Câu hỏi thường gặp & hỗ trợ',
      'terms_service': 'Điều Khoản Dịch Vụ',
      'privacy_policy': 'Chính Sách Bảo Mật',
      'legal_info': 'Thông tin pháp lý',
      'last_updated': 'Cập nhật lần cuối',
      'danger_zone': 'VÙNG NGUY HIỂM',
      'sign_out': 'Đăng Xuất',
      'delete_account': 'Xóa Tài Khoản',
      'cannot_undone': 'Hành động này không thể hoàn tác',
      'select_language': 'Chọn Ngôn Ngữ',
      'sign_out_confirm': 'Bạn có chắc muốn đăng xuất?',
      'delete_confirm':
          'Điều này sẽ xóa vĩnh viễn tài khoản và tất cả dữ liệu. Hành động này không thể hoàn tác.',

      // Home
      'tonight_vibes': 'Chương Trình Tối Nay',
      'explore': 'Khám Phá',
      'match': 'Ghép Nhóm',
      'miles_short': 'dặm',
      'see_all': 'Xem Tất Cả',
      'nearby_events': 'Kèo Gần Đây',
      'no_events_category': 'Không tìm thấy sự kiện nào trong danh mục này.',
      'current_location': 'VỊ TRÍ HIỆN TẠI',
      'join_vibe': 'THAM GIA',

      // Vibe Match
      'vibe_match_title': 'Ghép Vibe',
      'vibe_match_label': 'TƯƠNG HỢP',
      'vibe_match_headline': 'Độ tương hợp rất tốt!',
      'vibe_match_subtitle':
          'Bạn phù hợp với năng lượng và sở thích của nhóm này.',
      'vibe_match_why': 'Vì sao hợp nhóm',
      'vibe_match_summary_title': 'Tóm tắt vibe nhóm',
      'vibe_match_summary_body':
          'Một nhóm thoải mái thích đá bóng buổi tối rồi đi cà phê đêm. Năng lượng cao nhưng luôn chào đón người mới.',
      'vibe_match_going': 'đang tham gia',
      'vibe_match_join_event': 'Tham Gia Sự Kiện',
      'vibe_match_explore_matches': 'Khám Phá Kết Nối',
      'vibe_match_reason_football': 'Fan Bóng Đá',
      'vibe_match_reason_night': 'Cú Đêm',
      'vibe_match_reason_nearby': 'Ở gần (2km)',
      'vibe_match_reason_coffee': 'Yêu Cà Phê',
      'vibe_match_joined_title': 'Bạn đã vào nhóm',
      'vibe_match_joined_headline': 'Đã giữ chỗ cho tối nay',
      'vibe_match_joined_body':
          'Bạn đã tham gia sự kiện thành công. Chúng tôi sẽ cập nhật thông tin mới từ host.',
      'your_top_matches': 'Top Kết Nối Của Bạn',
      'top_matches_subtitle':
          'Dựa trên vibe gần đây và sở thích chung, chúng tôi nghĩ bạn sẽ hợp với những người này.',
      'reliable': 'Đáng Tin Cậy',
      'new': 'Mới',
      'late_risk': 'Nguy Cơ Trễ',
      'view_profile': 'Xem Hồ Sơ',
      'shared': 'Tương Đồng',
      'no_matches_yet': 'Hiện chưa có kết nối phù hợp.',
      'open_group_vibe': 'Mở vibe nhóm',
      'open_user_detail': 'Mở hồ sơ người dùng',
      'open_match_details': 'Mở chi tiết match',
      'vibe_check_title': 'Vibe Check',
      'vibe_check_loading_title': 'AI đang phân tích vibe...',
      'vibe_check_loading_desc':
          'Đang so sánh sở thích, bio và các tín hiệu tương hợp khác.',
      'vibe_check_error_title': 'Chưa xem được vibe',
      'vibe_check_with': 'Vibe với',
      'strengths': 'Điểm mạnh',
      'considerations': 'Cần lưu ý',
      'conversation_starters': 'Gợi ý bắt chuyện',
      'date_ideas': 'Kèo có thể rủ',
      'verdict': 'Kết luận',
      'verdict_strong': 'Rất đáng thử',
      'verdict_medium': 'Có thể thử nhẹ',
      'verdict_low': 'Nên tìm hiểu thêm',
      'personality_take': 'Người này như thế nào',
      'compatibility_conclusion': 'Kết luận độ hợp',
      'date_recommendation': 'Có nên mời đi chơi?',
      'next_step': 'Bước tiếp theo',
      'score_breakdown': 'Chi tiết điểm số',
      'bio_label': 'Bio',
      'lifestyle': 'Lifestyle',
      'event': 'Event',
      'common_interests': 'Sở thích chung',
      'group_vibe_check_title': 'Group Vibe Check',
      'group_vibe_loading_title': 'AI đang đọc vibe của nhóm...',
      'group_vibe_loading_desc':
          'Đang so sánh participants, chủ đề event và tín hiệu an toàn.',
      'group_vibe_error_title': 'Chưa xem được vibe nhóm',
      'update_profile': 'Cập nhật hồ sơ',
      'back_to_event': 'Quay lại event',
      'group_vibe_empty_error':
          'Event này chưa có đủ dữ liệu để phân tích vibe nhóm.',
      'group_vibe_bad_request':
          'Event này chưa có đủ người hoặc hồ sơ của bạn cần thêm bio/sở thích.',
      'group_vibe_access_denied':
          'Bạn cần được duyệt vào event trước khi xem vibe nhóm.',
      'group_strengths': 'Điểm mạnh của nhóm',
      'watchouts': 'Cần lưu ý',
      'suggested_actions': 'Hành động nên thử',
      'members': 'thành viên',
      'analyzed': 'phân tích',
      'group_recommendation_title': 'Nhóm này có hợp với bạn không?',
      'breakdown': 'Breakdown',
      'member_compatibility': 'Độ hợp với thành viên',
      'interest_alignment': 'Độ khớp sở thích',
      'event_fit': 'Độ hợp với event',
      'social_comfort': 'Mức thoải mái xã hội',
      'location_fit': 'Độ hợp địa điểm',
      'group_reliability': 'Độ tin cậy của nhóm',
      'top_matches_in_group': 'Top matches trong nhóm',
      'no_group_top_matches': 'Chưa có thành viên nổi bật để gợi ý.',
      'member': 'Thành viên',
      'fallback_insight_computed':
          'Insight được tạo bằng fallback từ dữ liệu đã tính.',
      'fallback_insight_prefix': 'Insight fallback',
      'match_details_title': 'Chi tiết match',
      'high_compatibility_found': 'Tìm thấy độ tương hợp cao',
      'compatibility_deep_dive': 'Phân tích độ tương hợp',
      'activity_style': 'Phong cách hoạt động',
      'schedule_match': 'Độ khớp lịch',
      'competitive': 'Cạnh tranh',
      'casual': 'Thoải mái',
      'intense': 'Nhiệt',
      'match_strengths_desc':
          'Rất hợp ở mảng thể thao. Cả hai đều thích hoạt động cuối tuần cường độ cao và có trình tennis tương đồng.',
      'match_considerations_desc':
          'Có 2 người dùng mới trên nền tảng. Dữ liệu lịch sử về độ tin cậy lịch trình còn ít.',
      'how_you_compare_to_group': 'Bạn so với nhóm thế nào',
      'your_score': 'Điểm của bạn',
      'group_avg': 'TB nhóm',
      'you_top_group': 'Bạn nằm trong top 15% của nhóm này',
      'avg': 'TB',
      'group_analysis': 'Phân tích nhóm',
      'exceptional_vibe': 'Vibe rất hợp',
      'exceptional_vibe_desc':
          'Nhóm này có độ khớp năng lượng rất cao. Rất hợp cho những buổi đi chơi dài và năng động.',
      'strongest_match': 'Match mạnh nhất',
      'low_pace_match': 'Match nhịp chậm',
      'group_personality': 'Tính cách nhóm',
      'group_personality_desc':
          'Phần lớn nhóm thích môi trường năng động, nhịp nhanh. Có thể điều chỉnh lộ trình để phù hợp hơn với nhịp thoải mái.',
      'suggest_route_adjustment': 'Gợi ý chỉnh lộ trình',
      'invite_to_event': 'Mời vào event',
      'high': 'Cao',
      'compatibility': 'Tương hợp',
      'reputation': 'Uy tín',
      'about_user': 'Về Sarah',
      'about_user_desc':
          'Luôn sẵn sàng đi cà phê ngẫu hứng hoặc hiking dài ở greenbelt. Muốn gặp những người thích thử quán ăn mới và trò chuyện sâu bên matcha.',
      'recent_activity': 'Hoạt động gần đây',
      'hosted_upper': 'ĐÃ HOST',
      'attended_upper': 'ĐÃ THAM GIA',
      'last_week': 'Tuần trước',
      'two_weeks_ago': '2 tuần trước',
      'meetups': 'Meetup',

      // Check-in
      'checkin_feature_title': 'Xác Thực Meetup',
      'checkin_title': 'Check-in',
      'checkin_choose_title': 'Chọn Check-in',
      'checkin_verifying_page_title': 'Đang xác thực check-in',
      'checkin_complete_title': 'Check-in hoàn tất',
      'checkin_trust_profile_title': 'Hồ sơ uy tín',
      'checkin_nav_explore': 'Khám phá',
      'checkin_nav_meetups': 'Meetup',
      'checkin_nav_scan': 'Quét',
      'checkin_nav_trust': 'Tin cậy',
      'checkin_method_section': 'Phương thức check-in',
      'checkin_verified_label': 'Đã xác thực',
      'checkin_method_hint': 'Chọn cách nhanh nhất đang có tại địa điểm.',
      'checkin_starts_in': 'Bắt đầu sau 15:00',
      'checkin_meeting_point': 'Điểm hẹn',
      'checkin_required_note': 'Check-in giúp duy trì điểm uy tín của bạn',
      'checkin_check_in': 'Check-in',
      'checkin_chat': 'Chat',
      'checkin_map': 'Bản đồ',
      'checkin_participants': 'Người tham gia',
      'checkin_confirmed_count': '3 đã xác nhận',
      'checkin_method_title': 'Bạn muốn check-in bằng cách nào?',
      'checkin_method_subtitle': 'Chọn phương thức có sẵn tại địa điểm meetup',
      'checkin_qr_method': 'Check-in QR',
      'checkin_qr_method_desc': 'Xác thực QR nhanh và dễ dàng',
      'checkin_nfc_method': 'Check-in NFC',
      'checkin_nfc_method_desc': 'Chạm điện thoại gần thẻ NFC',
      'checkin_recommended': 'GỢI Ý',
      'checkin_recommended_title': 'Gợi ý',
      'checkin_tap_to_verify': 'Chạm để xác thực',
      'checkin_qr_home_desc': 'Quét mã QR của event bằng camera.',
      'checkin_nfc_home_desc': 'Đưa điện thoại gần thẻ NFC của event.',
      'checkin_qr_home_footnote':
          'Phù hợp nhất cho event có host hoặc bàn check-in.',
      'checkin_qr_method_footnote': 'Phù hợp nhất cho bàn check-in của event.',
      'checkin_nfc_home_footnote': 'Hoạt động khi NFC đã bật trên thiết bị.',
      'checkin_nfc_method_footnote': 'Dùng NFC khi địa điểm có thẻ venue.',
      'checkin_gps_verified': 'GPS đã xác thực',
      'checkin_distance': 'Khoảng cách',
      'checkin_location_auto_verified':
          'Vị trí của bạn sẽ được tự động xác thực',
      'checkin_secure_checkin': 'Check-in bảo mật',
      'checkin_time': 'Thời gian',
      'checkin_location': 'Địa điểm',
      'checkin_confirmed': 'Đã xác nhận',
      'checkin_qr_scan_title': 'Quét mã QR tại địa điểm meetup',
      'checkin_qr_scan_hint': 'Đặt mã QR vào trong khung quét',
      'checkin_qr_frame_hint': 'Đặt mã QR vào trong khung.',
      'checkin_qr_requesting_camera': 'Đang xin quyền camera',
      'checkin_qr_camera_needed': 'Cần quyền camera để quét mã QR.',
      'checkin_qr_permission_denied': 'Quyền camera bị từ chối',
      'checkin_qr_permission_required':
          'Cần quyền camera để quét mã QR của event.',
      'checkin_retry': 'Thử lại',
      'checkin_qr_detected': 'Đã phát hiện mã QR',
      'checkin_preparing_verification': 'Đang chuẩn bị xác thực bảo mật...',
      'checkin_qr_unable_to_scan': 'Không thể quét mã QR',
      'checkin_qr_scan_error': 'Có lỗi khi quét. Vui lòng thử lại.',
      'checkin_qr_failed': 'Check-in QR thất bại. Vui lòng thử lại.',
      'checkin_qr_scan_heading': 'Quét mã QR của event',
      'checkin_qr_scan_desc': 'Để camera lấy nét vào mã tại bàn check-in.',
      'checkin_camera_ready': 'Camera đã sẵn sàng',
      'checkin_qr_camera_ready_desc':
          'Giữ mã QR phẳng và nằm trong khung đến khi xác thực hoàn tất.',
      'checkin_demo_verify': 'Thử xác thực',
      'checkin_verifying_title': 'Đang xác thực bạn đã đến...',
      'checkin_verifying_desc': 'Đang kiểm tra an toàn vị trí và thời gian',
      'checkin_gps_active': 'GPS đang bật',
      'checkin_encrypted': 'Đã mã hóa',
      'checkin_demo_result': 'Xem kết quả',
      'checkin_nfc_failed': 'Check-in NFC thất bại. Vui lòng thử lại.',
      'checkin_nfc_checking': 'Đang kiểm tra NFC',
      'checkin_nfc_checking_desc':
          'Đang kiểm tra thiết bị này có hỗ trợ NFC không.',
      'checkin_nfc_preparing': 'Đang chuẩn bị máy quét NFC',
      'checkin_nfc_ready': 'Sẵn sàng quét',
      'checkin_nfc_ready_desc': 'Giữ điện thoại gần thẻ NFC để check-in.',
      'checkin_nfc_detected': 'Đã phát hiện thẻ NFC',
      'checkin_nfc_unsupported': 'NFC không được hỗ trợ',
      'checkin_nfc_unsupported_desc':
          'Thiết bị này không hỗ trợ check-in bằng NFC.',
      'checkin_nfc_disabled': 'NFC đang tắt',
      'checkin_nfc_disabled_desc':
          'Bật NFC trong cài đặt thiết bị rồi thử lại.',
      'checkin_nfc_unable_to_start': 'Không thể khởi động NFC',
      'checkin_nfc_start_error': 'Có lỗi khi bắt đầu quét NFC.',
      'checkin_nfc_hint': 'Giữ phần trên của điện thoại sát thẻ NFC.',
      'checkin_nfc_waiting_title': 'Chạm điện thoại gần thẻ NFC',
      'checkin_nfc_waiting_desc': 'Đang chờ phát hiện...',
      'checkin_device_status': 'Trạng thái thiết bị',
      'checkin_nfc_result_title': 'Đã xác thực',
      'checkin_nfc_result_desc': 'Check-in thành công',
      'checkin_result_success_message': 'Bạn đã check-in thành công.',
      'checkin_already_checked_in': 'Đã check-in trước đó',
      'checkin_not_verified': 'Check-in chưa được xác thực',
      'checkin_attendance_verified': 'Đã xác thực tham dự',
      'checkin_already_verified_event': 'Event này đã được xác thực trước đó',
      'checkin_verified_status': 'Check-in đã xác thực',
      'checkin_method_label': 'Phương thức',
      'checkin_xp_awarded': '+15 XP đã được cộng vào điểm uy tín',
      'checkin_view_trust': 'Xem hồ sơ uy tín',
      'checkin_reputation_level': 'Cấp uy tín: Elite Explorer',
      'checkin_trust_score': 'Điểm uy tín',
      'checkin_top_percent': 'Top 2% cộng đồng trong tháng này',
      'checkin_attendance_rate': 'Tỷ lệ tham dự',
      'checkin_meetup_streak': 'Chuỗi meetup',
      'checkin_earned_badges': 'Huy hiệu đã nhận',
      'checkin_missing_context': 'Check-in này thiếu ngữ cảnh meetup.',
      'checkin_missing_qr_context': 'Thiếu ngữ cảnh match cho check-in QR.',
      'checkin_missing_nfc_context': 'Thiếu ngữ cảnh match cho check-in NFC.',
      'checkin_missing_method_context_prefix': 'Thiếu ngữ cảnh match cho',
      'checkin_already_checked_in_meetup': 'Bạn đã check-in cho meetup này.',
      'checkin_not_available_now': 'Hiện chưa thể check-in.',
      'checkin_method_not_available': 'không khả dụng cho meetup này.',
      'checkin_method_disabled': 'hiện đang bị tắt.',
      'checkin_not_participant': 'Bạn chưa phải người tham gia meetup này.',
      'checkin_join_not_approved': 'Yêu cầu tham gia của bạn chưa được duyệt.',
      'checkin_match_cancelled': 'Meetup này không còn hoạt động.',
      'checkin_outside_time_window':
          'Check-in chỉ khả dụng gần thời gian meetup.',
      'checkin_location_not_supported':
          'Meetup này chưa có địa điểm check-in được hỗ trợ.',
      'checkin_no_active_method':
          'Meetup này chưa bật phương thức check-in nào.',
      'checkin_no_active_nfc': 'Venue này chưa có thẻ NFC đang hoạt động.',
      'checkin_no_active_qr': 'Venue này chưa có mã QR đang hoạt động.',
      'checkin_missing_gps_coordinates':
          'Venue thiếu tọa độ GPS cho check-in QR.',
      'checkin_missing_qr_radius': 'Venue thiếu bán kính check-in QR.',
      'checkin_service_unavailable': 'Dịch vụ check-in chưa khả dụng.',
      'checkin_unable_current_location':
          'Không thể lấy vị trí GPS hiện tại. Vui lòng thử lại.',
      'checkin_hold_device_near_nfc': 'Giữ thiết bị gần thẻ NFC của event.',
      'checkin_nfc_turned_off_try_again':
          'NFC đang tắt. Hãy bật NFC rồi thử lại.',
      'checkin_unable_start_nfc_try_again':
          'Không thể bắt đầu quét NFC. Vui lòng thử lại.',
      'checkin_location_service_required':
          'Cần bật dịch vụ vị trí để check-in QR.',
      'checkin_location_permission_required':
          'Cần quyền vị trí để check-in QR.',
      'checkin_verified_ios_alert': 'Check-in đã xác thực.',
      'checkin_checked_in_title': 'Bạn đã check-in',
      'checkin_checked_in_desc':
          'Lượt đến của bạn đã được xác thực. Chúc bạn vui ở meetup.',
      'checkin_auto_verify_note':
          'Thẻ NFC và khung thời gian sẽ được tự động kiểm tra.',
      'checkin_fallback_title': 'Check-in meetup',
      'checkin_fallback_location_name': 'Địa điểm event',
      'checkin_fallback_location_address': 'Địa điểm sẽ được venue xác thực.',
      'checkin_fallback_time': 'Meetup đã lên lịch',
      'checkin_member_verified': 'Thành viên đã xác thực',
      'checkin_member_top_contributor': 'Người đóng góp nổi bật',
      'checkin_member_new': 'Thành viên mới',
      'checkin_status_arrived': 'Đã đến',
      'checkin_status_pending': 'Đang chờ',
      'checkin_status_late': 'Trễ',
      'checkin_status_late_risk': 'Nguy cơ trễ',
      'checkin_status_no_show': 'Không đến',
      'checkin_badge_early_bird': 'Đi sớm',
      'checkin_badge_reliable_host': 'Host đáng tin',
      'checkin_badge_explorer': 'Nhà khám phá',
      'checkin_badge_top_guest': 'Khách nổi bật',

      // Find in Crowd
      'finder_title': 'Tìm Trong Đám Đông',
      'finder_find_in_crowd': 'Tìm trong đám đông',
      'finder_start': 'Bắt đầu tìm',
      'finder_cancel': 'Hủy',
      'finder_waiting': 'Đang chờ',
      'finder_accept': 'Chia sẻ vị trí tạm thời',
      'finder_decline': 'Để sau',
      'finder_stop': 'Dừng tìm',
      'finder_continue': 'Tiếp tục',
      'finder_back_to_meeting': 'Về buổi hẹn',
      'finder_find_again': 'Tìm lại',
      'finder_temporary_live_location': 'Vị trí trực tiếp tạm thời',
      'finder_request_title': 'Yêu cầu Finder',
      'finder_live_location_request': 'Yêu cầu vị trí trực tiếp',
      'finder_request_expired': 'Yêu cầu Finder đã hết hạn.',
      'finder_request_cancelled': 'Yêu cầu Finder đã hủy.',
      'finder_request_was_cancelled': 'Yêu cầu Finder đã bị hủy.',
      'finder_request_declined': 'Yêu cầu Finder đã bị từ chối.',
      'finder_request_ended': 'Yêu cầu Finder đã kết thúc.',
      'finder_request_sent': 'Đã gửi yêu cầu',
      'finder_waiting_response': 'Đang chờ phản hồi...',
      'finder_waiting_accept_prefix': 'Đang chờ',
      'finder_waiting_accept_suffix': 'chấp nhận...',
      'finder_location_starts_after_accept':
          'Chỉ bắt đầu chia sẻ vị trí sau khi họ chấp nhận yêu cầu này.',
      'finder_cancel_request': 'Hủy yêu cầu',
      'finder_request_expired_short': 'Yêu cầu đã hết hạn',
      'finder_request_expires_in': 'Yêu cầu hết hạn sau',
      'finder_finding': 'Đang tìm',
      'finder_finding_prefix': 'Đang tìm',
      'finder_waiting_location': 'Đang chờ',
      'finder_live': 'Live',
      'finder_waiting_shared_location': 'Đang chờ vị trí được chia sẻ',
      'finder_away': 'cách bạn',
      'finder_reconnecting': 'Đang kết nối lại',
      'finder_weak_gps': 'GPS yếu',
      'finder_live_signal': 'Tín hiệu live',
      'finder_stale_location_note':
          'Đang chờ vị trí mới nhất của người kia. Chia sẻ sẽ tiếp tục khi cả hai app đang hoạt động.',
      'finder_final_guidance_note':
          'Đã có hướng dẫn cuối. Di chuyển chậm và quan sát xung quanh ở vài mét cuối.',
      'finder_active_sharing_note':
          'Chia sẻ vị trí live đang bật. Đi theo thẻ chỉ hướng đến khi đủ gần để mở hướng dẫn cuối.',
      'finder_open_final_guidance': 'Mở hướng dẫn cuối',
      'finder_final_guidance_locked': 'Hướng dẫn cuối mở khi còn trong 30m',
      'finder_stop_sharing': 'Dừng chia sẻ',
      'finder_nearby': 'Ở gần',
      'finder_final_approach': 'Tiếp cận cuối',
      'finder_nearby_label': 'ở gần',
      'finder_toward_marker': 'về phía điểm đánh dấu',
      'finder_very_close': 'Rất gần',
      'finder_they': 'Họ',
      'finder_should_be_around': 'đang ở ngay gần bạn.',
      'finder_is_close_keep_moving':
          'đang ở gần. Tiếp tục đi về phía điểm đánh dấu.',
      'finder_look_around_note':
          'Quan sát xung quanh, vẫy tay hoặc nhắn tin cho họ. GPS có thể lệch ở vài mét cuối.',
      'finder_distance_updates_note':
          'Khoảng cách cập nhật live từ GPS. Đi chậm để Finder giữ mũi tên ổn định.',
      'finder_visual_title': 'Visual Finder',
      'finder_gps_based_direction': 'Chỉ hướng bằng GPS',
      'finder_approx_direction': 'hướng xấp xỉ',
      'finder_exit_ar': 'Thoát AR',
      'finder_stop_short': 'Dừng',
      'finder_ended_title': 'Finder đã kết thúc',
      'finder_session_expired': 'Phiên đã hết hạn',
      'finder_location_stopped': 'Chia sẻ vị trí đã dừng',
      'finder_session_expired_title': 'Phiên Finder đã hết hạn',
      'finder_ended_panel_title': 'Finder đã kết thúc',
      'finder_ended_message':
          'Vị trí tạm thời của bạn không còn được chia sẻ trong phiên Finder này.',
      'finder_keep_finding': 'Tiếp tục tìm',
      'finder_your_partner': 'người kia',
      'finder_stop_sharing_question': 'Dừng chia sẻ vị trí?',
      'finder_stop_message_prefix':
          'Việc này sẽ kết thúc phiên Finder cho cả bạn và',
      'finder_stopping': 'Đang dừng...',
      'finder_open_from_event': 'Mở từ event',
      'finder_choose_member_first': 'Hãy chọn một thành viên đã check-in trước',
      'finder_continue_event_members': 'Tiếp tục đến danh sách thành viên',
      'finder_consent_flow_desc':
          'Finder là luồng GPS live dựa trên đồng thuận cho hai người trong cùng event.',
      'finder_back_to_events': 'Quay lại event',
      'finder_view_members': 'Xem thành viên',
      'finder_find_question_prefix': 'Tìm',
      'finder_find_question_suffix': 'trong đám đông?',
      'finder_start_desc_prefix': 'Bạn và',
      'finder_start_desc_suffix':
          'sẽ tạm thời chia sẻ vị trí xấp xỉ để tìm nhau nhanh hơn.',
      'finder_you': 'Bạn',
      'finder_request_wants_title_suffix': 'muốn tìm bạn trong đám đông',
      'finder_request_wants_desc_suffix':
          'muốn chia sẻ vị trí xấp xỉ tạm thời để hai bạn tìm nhau nhanh hơn.',
      'finder_for_finding_only': 'Chỉ dùng để tìm nhau',
      'finder_safety_notice':
          'Chia sẻ tạm thời tự kết thúc sau 10 phút. Bạn có thể dừng bất cứ lúc nào.',
      'finder_guidance_keep_apps_open':
          'Giữ cả hai app đang mở để Finder nhận cập nhật live.',
      'finder_signal_stale': 'Tín hiệu đã cũ. Nhắc họ giữ app đang mở.',
      'finder_gps_weak_open_area':
          'GPS yếu. Di chuyển ra khu vực thoáng hơn để chỉ hướng ổn định.',
      'finder_no_target_position': 'Chưa có vị trí mục tiêu',
      'finder_camera_note_prefix': 'Hướng xấp xỉ bằng GPS đến',
      'finder_camera_note_suffix':
          'Tiếp tục quan sát bằng mắt khi bạn đến gần.',
      'finder_distance': 'Khoảng cách',
      'finder_direction': 'Hướng',
      'finder_current_gps_position': 'Vị trí GPS hiện tại',
      'finder_gps_permission_required': 'Cần quyền GPS',
      'finder_allow_location_start':
          'Cho phép truy cập vị trí để bắt đầu Finder.',
      'finder_getting_location': 'Đang lấy vị trí...',
      'finder_refresh_gps': 'Làm mới GPS',
      'finder_allow_gps_access': 'Cho phép GPS',
      'finder_live_participant': 'Người tham gia Finder live',
      'finder_sharing': 'Đang chia sẻ',
      'finder_location_permission_needed': 'Cần quyền vị trí để dùng Finder.',
      'finder_gps_accuracy_weak':
          'Độ chính xác GPS quá yếu. Di chuyển ra khu vực thoáng và thử lại.',
      'finder_session_expired_message': 'Phiên Finder đã hết hạn.',
      'finder_location_sharing_stopped': 'Chia sẻ vị trí đã dừng.',
      'finder_gps_off': 'GPS đang tắt. Bật GPS để dùng Finder.',
      'finder_enable_location_settings':
          'Bật vị trí trong cài đặt app để dùng Finder.',
      'finder_session_inactive':
          'Phiên Finder này đã kết thúc hoặc không còn hoạt động.',
      'finder_session_no_access':
          'Bạn không còn quyền truy cập phiên Finder này.',
      'finder_session_not_found': 'Không tìm thấy phiên Finder này.',
      'finder_member_not_available': 'Người này hiện chưa khả dụng cho Finder.',
      'finder_request_expired_error': 'Yêu cầu này đã hết hạn.',
      'finder_session_conflict':
          'Một trong hai bạn đang ở trong phiên Finder khác.',
      'finder_request_already_exists': 'Bạn đã có một yêu cầu Finder đang chờ.',
      'finder_north': 'Bắc',
      'finder_north_east': 'Đông Bắc',
      'finder_east': 'Đông',
      'finder_south_east': 'Đông Nam',
      'finder_south': 'Nam',
      'finder_south_west': 'Tây Nam',
      'finder_west': 'Tây',
      'finder_north_west': 'Tây Bắc',
      'finder_walk_toward': 'Đi về phía',
      'finder_move': 'Di chuyển',
      'finder_toward': 'về phía',
      'finder_keep_straight': 'Tiếp tục đi thẳng',
      'finder_turn_right': 'Rẽ phải',
      'finder_turn_around': 'Quay lại',
      'finder_turn_left': 'Rẽ trái',
      'finder_go_straight_for': 'Đi thẳng thêm',
      'finder_slight_right_then': 'Chếch phải, rồi',
      'finder_turn_right_then': 'Rẽ phải, rồi',
      'finder_turn_around_then': 'Quay lại, rồi',
      'finder_turn_left_then': 'Rẽ trái, rồi',
      'finder_slight_left_then': 'Chếch trái, rồi',
      'finder_approx_compass': 'Hướng la bàn xấp xỉ',
      'finder_phone_heading': 'Hướng đi theo hướng điện thoại',
      'finder_movement_heading': 'Hướng đi theo chuyển động của bạn',
      'finder_straight_ahead': 'Thẳng phía trước',
      'finder_right': 'bên phải',
      'finder_left': 'bên trái',
      'finder_turn_degrees': 'Xoay',
      'finder_degrees': 'độ',
      'finder_move_closer_unlock': 'Di chuyển gần hơn để mở hướng dẫn cuối.',
      'finder_improving_accuracy':
          'Đang cải thiện độ chính xác vị trí trước khi mở hướng dẫn cuối.',
      'finder_waiting_latest_partner':
          'Đang chờ vị trí mới nhất của người kia trước khi mở hướng dẫn cuối.',
      'finder_gps_ready_final': 'GPS đã sẵn sàng cho hướng dẫn cuối.',

      // Map
      'search_placeholder': 'Tìm vibe, địa điểm hoặc danh mục...',
      'no_vibes_found': 'Không tìm thấy vibe nào ở đây.',

      // Activity
      'my_activity': 'Hoạt Động',
      'hosting': 'Đang tổ chức',
      'hosted': 'Đã tổ chức',
      'attending': 'Đang tham gia',
      'past': 'Đã tham gia',
      'no_events_yet': 'Chưa có sự kiện nào',
      'starts_in_days': 'Bắt đầu trong 2 ngày',
      'ended': 'Đã kết thúc',
      'manage': 'Quản lý',
      'check_in': 'Điểm danh',
      'rate_experience': 'Đánh giá',

      // Create Event
      'create_vibe': 'Tạo Kèo',
      'whats_vibe': 'Vibe Của Bạn?',
      'give_persona': 'Đặt tên cho sự kiện',
      'event_category': 'Danh Mục Sự Kiện',
      'vibe_tags': 'Thẻ Vibe',
      'schedule_size': 'Lịch Trình & Quy Mô',
      'when_how_many': 'Khi nào và bao nhiêu người?',
      'destination': 'Địa Điểm',
      'where_happening': 'Diễn ra ở đâu?',
      'create_event_title_new': 'Tạo Sự Kiện',
      'event_hero_title': 'Thiết kế sự kiện chuẩn cao cấp',
      'event_hero_subtitle':
          'Bố cục rõ ràng, trải nghiệm mượt và chuyên nghiệp.',
      'event_section_core': 'Thông Tin Chính',
      'event_section_core_subtitle':
          'Nhận diện sự kiện, danh mục, tag và hình ảnh.',
      'event_section_schedule': 'Lịch Trình & Sức Chứa',
      'event_section_schedule_subtitle':
          'Thời gian bắt đầu/kết thúc và giới hạn người tham gia.',
      'event_section_location': 'Địa Điểm',
      'event_section_location_subtitle':
          'Thông tin nơi tổ chức và tọa độ bản đồ.',
      'event_section_advanced': 'Metadata Nâng Cao',
      'event_section_advanced_subtitle':
          'Host, trạng thái, quyền hiển thị và điểm AI.',
      'event_field_id': 'Mã sự kiện',
      'event_field_title': 'Tiêu đề',
      'event_field_title_hint': 'Vibe của sự kiện là gì?',
      'event_field_description': 'Mô tả',
      'event_field_description_hint':
          'Mô tả đối tượng phù hợp và trải nghiệm mong đợi.',
      'event_field_category': 'Danh mục',
      'event_field_vibe_tags': 'Thẻ vibe',
      'event_field_add_tag': 'Thêm tag',
      'event_field_add_tag_hint': 'Chill, Competitive, Networking...',
      'event_field_photo_urls': 'Đường dẫn ảnh',
      'event_field_add_photo_url': 'Thêm URL ảnh',
      'event_field_start_date': 'Ngày bắt đầu',
      'event_field_start_time': 'Giờ bắt đầu',
      'event_field_end_date': 'Ngày kết thúc',
      'event_field_end_time': 'Giờ kết thúc',
      'event_field_max_participants': 'Số lượng tối đa',
      'event_field_current_participants': 'Số lượng hiện tại',
      'event_field_search_place': 'Tìm địa điểm',
      'event_field_search_place_hint': 'Nhập tối thiểu 2 ký tự...',
      'event_field_location_name': 'Tên địa điểm',
      'event_field_location_name_hint': 'District 1 Center',
      'event_field_location_address': 'Địa chỉ',
      'event_field_location_address_hint': 'Ho Chi Minh City, Vietnam',
      'event_field_latitude': 'Vĩ độ',
      'event_field_longitude': 'Kinh độ',
      'event_field_host_id': 'Host ID',
      'event_field_host_name': 'Tên host',
      'event_field_host_avatar': 'URL ảnh host',
      'event_field_place_id': 'Place ID',
      'event_field_place_id_hint': 'Mã địa điểm từ hệ thống ngoài (tuỳ chọn)',
      'event_field_status': 'Trạng thái',
      'event_field_is_elite_only': 'Chỉ hiển thị cho Elite',
      'event_field_is_public': 'Hiển thị công khai',
      'event_field_is_joined': 'Người dùng hiện tại đã tham gia',
      'event_field_match_score': 'Điểm tương hợp',
      'event_field_participant_ids': 'Danh sách participant IDs',
      'event_field_participant_ids_hint': 'user-101, user-202...',
      'event_field_created_at': 'Thời điểm tạo',
      'event_status_draft': 'Bản nháp',
      'event_status_active': 'Đang hoạt động',
      'event_status_cancelled': 'Đã hủy',
      'event_status_completed': 'Đã hoàn thành',
      'event_category_sports': 'Thể thao',
      'event_category_dining': 'Ăn uống',
      'event_category_social': 'Giao lưu',
      'event_category_arts': 'Nghệ thuật',
      'event_category_outdoors': 'Ngoài trời',
      'event_category_gaming': 'Gaming',
      'event_create_button': 'Tạo Sự Kiện',
      'event_create_loading': 'Đang tạo sự kiện...',
      'event_create_success': 'Tạo sự kiện thành công!',
      'event_create_error': 'Lỗi',
      'event_validation_title_description': 'Vui lòng nhập tiêu đề và mô tả.',
      'event_validation_location': 'Vui lòng nhập tên địa điểm và địa chỉ.',
      'event_validation_end_time':
          'Thời gian kết thúc phải sau thời gian bắt đầu.',
      'edit_event_title': 'Chỉnh Sửa Sự Kiện',
      'edit_event_loading': 'Đang lưu thay đổi...',
      'edit_event_success': 'Cập nhật sự kiện thành công!',
      'edit_event_error': 'Lỗi cập nhật sự kiện',
      'edit_event_validation_capacity':
          'Sức chứa không được thấp hơn số lượng người tham gia hiện tại ({current}).',
      'edit_event_read_only_fields':
          'Địa điểm và lịch trình được khóa sau khi tạo kèo để tránh gây hiểu lầm cho người tham gia.',

      // New additions for UI
      'appearance_desc': 'Cài đặt giao diện hiện đang đồng bộ với chế độ tối.',
      'privacy': 'Quyền Riêng Tư',
      'privacy_desc': 'Cài đặt Quyền riêng tư sẽ có trong bản cập nhật tới.',
      'change_password_desc': 'Một email hướng dẫn đổi mật khẩu đã được gửi.',
      'payout': 'Thanh Toán',
      'payout_desc': 'Tài khoản Stripe của bạn đã được kết nối thành công.',
      'help_desc': 'Đang chuyển hướng đến cổng hỗ trợ...',
      'terms': 'Điều Khoản',
      'terms_desc': 'Đang tải điều khoản dịch vụ...',
      'version': 'Phiên bản 1.0.0 (Build 42)',
      'made_with': 'Làm với 💜 tại TP.HCM',
      'language_changed': 'Đã đổi ngôn ngữ sang',
      'your_display_name': 'Tên hiển thị của bạn',
      'name_required': 'Vui lòng nhập tên',
      'your_username': 'Tên người dùng của bạn',
      'username_required': 'Vui lòng nhập tên người dùng',
      'email': 'EMAIL',
      'your_email': 'Email của bạn',
      'tell_people': 'Giới thiệu về bản thân...',
      'your_city': 'Thành phố của bạn',
      'tap_change_photo': 'Chạm để đổi ảnh',
      'avatar_updated': 'Đã cập nhật ảnh đại diện!',
      'message': 'Nhắn tin',
      'follow': 'Theo dõi',
      'following': 'Đang theo dõi',
    },
    'ja': {
      'app_name': 'VibePulse',
      'settings': '設定',
      'edit_profile': 'プロフィール編集',
      'interests': '趣味',
      'badges_gallery': 'バッジギャラリー',
      'activity_history': 'アクティビティ履歴',
      'view_all': 'すべて見る',
      'dark_mode': 'ダークモード',
      'language': '言語',
      'sign_out': 'ログアウト',
    },
    'ko': {
      'app_name': 'VibePulse',
      'settings': '설정',
      'edit_profile': '프로필 편집',
      'interests': '관심사',
      'badges_gallery': '배지 갤러리',
      'activity_history': '활동 내역',
      'view_all': '모두 보기',
      'dark_mode': '다크 모드',
      'language': '언어',
      'sign_out': '로그아웃',
    },
    'fr': {
      'app_name': 'VibePulse',
      'settings': 'Paramètres',
      'edit_profile': 'Modifier le profil',
      'interests': 'Centres d\'intérêt',
      'badges_gallery': 'Galerie de badges',
      'activity_history': 'Historique d\'activité',
      'view_all': 'TOUT VOIR',
      'dark_mode': 'Mode sombre',
      'language': 'Langue',
      'sign_out': 'Déconnexion',
    },
  };

  static String langCodeToName(String code) {
    switch (code) {
      case 'en':
        return 'English';
      case 'vi':
        return 'Tiếng Việt';
      case 'ja':
        return '日本語';
      case 'ko':
        return '한국어';
      case 'fr':
        return 'Français';
      default:
        return code;
    }
  }

  static String langNameToCode(String name) {
    switch (name) {
      case 'English':
        return 'en';
      case 'Vietnamese':
      case 'Tiếng Việt':
        return 'vi';
      case 'Japanese':
      case '日本語':
        return 'ja';
      case 'Korean':
      case '한국어':
        return 'ko';
      case 'French':
      case 'Français':
        return 'fr';
      default:
        return 'en';
    }
  }
}
