name: PR Check

on:
  pull_request:
    branches:
      - dev # Đã sửa thành dev
      - main

# Tự động hủy luồng cũ nếu có commit mới được push lên cùng 1 PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Check Code and Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache build_runner
        uses: actions/cache@v4
        with:
          path: |
            .dart_tool/build
          key: ${{ runner.os }}-build-${{ hashFiles('lib/**') }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      # ĐÃ SỬA: Thêm flavor và target
      - name: Build APK (Debug)
        run: flutter build apk --debug --flavor dev --target lib/main_dev.dart
